### PR TITLE
Fix Compile Warnings

### PR DESCRIPTION
**Pull request by Arc-huangjingtong**
# PR Details

## Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)

## Checklist
 its a very simple PR , fix a little Compile Warnings in Rider IDE

### CODE REVIEW

**Comment by VaclavElias** [comment]
Thank you @Arc-huangjingtong 🙂. Please, could you update your PR and keep the original code styling and formatting, so the reviewers can focus on your specific code updates/changes and to keep consistency with the rest of our code base.

**Comment by Arc-huangjingtong** [comment]
thanks this is my first PR 😄

**Comment by Arc-huangjingtong** [comment]
@dotnet-policy-service agree

**Comment by VaclavElias** [comment]
We all remember our first PR 🤣

**Comment by Eideren** [comment]
Thanks !

**Pull request merged**
