### PR TITLE
[Build] Couple of fixes to get it building with latest Visual Studio

### PR DESCRIPTION
**Pull request by azeno**
## Description

Not sure I did something completely wrong but with the following changes I could successfully compile again with latest VS (16.10.3). I was working on the `master-4.0` branch.

## Types of changes

- [ ] Docs change / refactoring / dependency upgrade
- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist

- [ ] My change requires a change to the documentation.
- [ ] I have added tests to cover my changes.
- [x] All new and existing tests passed.

### CODE REVIEW

**Comment by xen2** [comment]
Sorry I wanted to fix the build server first but this will take a few more days.
This is probably fine so I will merge it.

**Comment by xen2** [comment]
@azeno Curious, you remember what was the issue with `net5.0-windows` => `net5.0-windows7.0`?
I wonder if it should be ported to `master`.

**Comment by azeno** [comment]
See my commit message - I put a link there. Didn't really look too deep into it.

**Comment by xen2** [comment]
Thanks, I didn't see it.
Let me check if we need to update other places then (I could see some other references to `net5.0-windows` without `7.0`.

**Comment by azeno** [comment]
Well as long as there's no need don't. Once we're on 4.0 and these build issues persist I'll come back here :)

**Pull request merged**
