### PR TITLE
Use flip model in Direct3D11

### PR DESCRIPTION
**Pull request by azeno**
# PR Details

## Description

As recommended by Microsoft this PR uses the flip model in Direct3D11. A rather good overview with useful information & links can be found [here](https://walbourn.github.io/care-and-feeding-of-modern-swapchains/).

## Related Issue

#1344 

## Motivation and Context

Comparison of the example game
without flip model
image

with flip model
image

In another test where we only rendered a white quad in 1920x1200 (no post-effects) the GPU usage dropped from 20% to 0%.

## Types of changes

- [ ] Docs change / refactoring / dependency upgrade
- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist

- [ ] My change requires a change to the documentation.
- [ ] I have added tests to cover my changes.
- [x] All new and existing tests passed.

### CODE REVIEW

**Review by manio143 — APPROVED** [review]

**Review by tebjan — APPROVED** [review]

**Comment by tebjan** [comment]
Awesome, thanks!

**Comment by Eideren** [comment]
Just a small question, it looks like this is disabled if we're even using msaa - unless ours already resolves and the description is the one of the resolved buffer ?

**Comment by azeno** [comment]
True - I was under the impression in multi sampling the resolve was already handled in a separate target anyways? But you're right should be checked.

**Comment by azeno** [comment]
Ah wait, this PR is ok, with msaa it simply falls back to the old behaviour. It would be a separate quest to enable the flip model with msaa.

**Pull request merged**
