### PR TITLE
Fix to stop the visual studio installer exiting with code -1 during prerequisites install

### PR DESCRIPTION
**Pull request by Zeroto**
# PR Details

Moved vs prerequisite install before the other prerequisite installs.

## Description

The prerequisites installer somehow keeps the msiexec service in an installing state even though the installer is already finished and closed. This causes the visual studio installer to refuse to install because it thinks there is still an other installer running.

By installing the visual studio prerequisite before installing the other prequisites this problem is avoided. This is a hack because the windows installer state will still be wrong after this, but this will at least allow people to install stride properly without encountering an error that they can't easily solve. The windows installer being in a wrong state will most likely not cause any other problems for the user, because the next windows installer will detect the wrong state and fix it, or in the case of the visual studio installer it will fix it after hitting retry or restarting the visual studio installer(this will not happen when it is run in passive mode such as during the prerequisite install).

The proper solution for not ending up in this state would be in the advanced installer script/version. However, I could not find any online solutions for this or other people with the same problem.

## Related Issue

#653

## Types of changes

- [ ] Docs change / refactoring / dependency upgrade
- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist

- [ ] My change requires a change to the documentation.
- [ ] I have added tests to cover my changes.
- [ ] All new and existing tests passed.

### CODE REVIEW

**Comment by tebjan** [comment]
oh wow, that looks like a nice one!

**Comment by xen2** [comment]
Interesting, so it was all due to our own prerequisite installer!

**Comment by xen2** [comment]
It might be worth asking the Advanced Installer team/support about it.

**Comment by xen2** [comment]
@Zeroto How did you notice/check this msiexec state? Is there any tool or command line I can use to check the current state?

**Comment by Zeroto** [comment]
Sorry for the late reply, busy with my moving

No, as far as I know there is not anything available that will tell you the state of the service. My process was more a deduction of seeing what tasks were running and experimenting with running various installers in a different order and seeing the effects. I do remember encountering a few forum posts about people have similar problems (unrelated to stride)

**Pull request merged**
