### PR TITLE
Get rid of P/Invoke SizeOf.

### PR DESCRIPTION
**Pull request by ericwj**
# PR Details

Get rid of P/Invoke SizeOf.

## Description

Eliminates all references to `Stride.Core.Interop.SizeOf<T>()`.

## Related Issue

#1461 

## Motivation and Context

See issue.

## Types of changes

- [x] ~Docs change~ / refactoring / ~dependency upgrade~
- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [x] Breaking change (fix or feature that would cause existing functionality to change)
  - Use of `Utilities.SizeOf<T>()` and `Utilities.SizeOf<T>(T[])` will now produce warnings with text suggesting alternatives

## Checklist

- [ ] My change requires a change to the documentation.
- [ ] I have added tests to cover my changes.
- [ ] All new and existing tests passed.

All tests that pass in `master` on my computer pass in this branch too. `TestCopyPasteEntityAsChild` didn't pass running all tests from this branch while it passed in `master`, but passed when stepping through.

### CODE REVIEW

**Review by manio143 — APPROVED** [review]
Looks good. I've tested Starbreach on it and it works fine.
Please mark the "breaking change" in the PR description, because you're removing two methods from the `Utilities` class rather than marking them obsolete.
And while fixing whitespace isn't bad, too much of it can make PRs harder to review, so for the future I'd advise keeping it to the minimum relevant to the neighbourhood of code being changed.

**Comment by ericwj** [comment]
Oh yes, I must've overlooked that `Utilities` is in fact public.

**Comment by xen2** [comment]
Maybe it can be left as Deprecated/Obsolete on Utilities class until 4.2 so we can release it in 4.1?

**Comment by ericwj** [comment]
I left out `internal static int UnsafeSizeOf<T>()` because it is internal.

**Pull request merged**
