### PR TITLE
updated missed dotnet 6 reference in readme

### PR DESCRIPTION
**Pull request by Doprez**
# PR Details

Updated dotnet download link in the readme.

## Motivation and Context

.NET 8 is now needed instead of 6 for building the app.

## Types of changes

- [x] Docs change / refactoring / dependency upgrade
- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist

- [ ] My change requires a change to the documentation.
- [ ] I have added tests to cover my changes.
- [ ] All new and existing tests passed.
- [ ] **I have built and run the editor to try this change out.**

### CODE REVIEW

**Comment by VaclavElias** [comment]
Ohh, that reminds me, that we have to update also this page. Should it have mentioned SDK?

https://stride-doc-staging.azurewebsites.net/latest/en/manual/requirements/index.html

**Comment by Doprez** [comment]
ah yep, probably need to search for .NET 6 in a few places then lol.

**Comment by VaclavElias** [comment]
No problem. @Aggror, I wonder if we should update that page, as we are not mentioning anything about Development Prerequisites. Probably we need to move it away from https://github.com/stride3d/stride and place accordingly to this page https://stride-doc-staging.azurewebsites.net/latest/en/manual/requirements/index.html 

And further place links for devs prerequisites and contributing prerequisites to https://github.com/stride3d/stride, so we can always update it in one place, wherever it will be wiki on Stride Docs..

**Comment by Eideren** [comment]
Thanks :)

**Comment by VaclavElias** [comment]
I forgot the mention that correct name is `.NET SDK` and not `DotNET SDK`

**Pull request merged**
