### PR TITLE
Fixes a dead lock in the effect system

### PR DESCRIPTION
**Pull request by azeno**
# PR Details

## Description

The `DynamicEffectInstance` does a blocking wait on the result of the effect system. In there a continuation is created in case the compilation task is not yet finished. In case that continuation got scheduled on the calling thread we ended up in a dead lock.

## Related Issue

https://github.com/TheFuseLab/VL.Fuse/issues/51

## Types of changes

- [ ] Docs change / refactoring / dependency upgrade
- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist

- [ ] My change requires a change to the documentation.
- [ ] I have added tests to cover my changes.
- [x] All new and existing tests passed.

### CODE REVIEW

**Comment by azeno** [comment]
Sure I could try but not getting SpaceEscape to compile

grafik

**Comment by azeno** [comment]
master-4.0 is also crashing when opening SpaceEscape, this is the log:
```

Application: GameStudio
UserEmail: 
UserMessage: 
StrideVersion: 4.0.1.1
GameStudioVersion: 4
ThreadName: EditorGameThread (Scene)
CrashLocation: 1
ProcessID: 11540
DefaultGraphicProfile: Level_9_3
OpenedAssets: 
LastActions: 
CurrentDirectory: %USERPROFILE%\source\repos\stride\sources\editor\Stride.GameStudio\bin\Debug\net472
CommandArgs: 
OsVersion: Microsoft Windows 10 Pro 10.0.19041 x64
ProcessorCount: 12
Exception: AggregateException: One or more errors occurred.
   at System.Threading.Tasks.Task`1.GetResultCore(Boolean waitCompletionNotification)
   at Stride.Shaders.Compiler.TaskOrResult`1.WaitForResult()
   at Stride.Rendering.DynamicEffectInstance.ChooseEffect(GraphicsDevice graphicsDevice)
   at Stride.Rendering.EffectInstance.UpdateEffect(GraphicsDevice graphicsDevice)
   at Stride.Rendering.Images.ImageEffectShader.DrawCore(RenderDrawContext context)
   at Stride.Rendering.RendererBase.Draw(RenderDrawContext context)
   at Stride.Rendering.Images.LuminanceEffect.DrawCore(RenderDrawContext context)
   at Stride.Rendering.RendererBase.Draw(RenderDrawContext context)
   at Stride.Rendering.Images.PostProcessingEffects.DrawCore(RenderDrawContext context)
   at Stride.Rendering.RendererBase.Draw(RenderDrawContext context)
   at Stride.Rendering.Images.PostProcessingEffects.Draw(RenderDrawContext drawContext, RenderOutputValidator outputValidator, Texture[] inputs, Texture inputDepthStencil, Texture outputTarget)
   at Stride.Rendering.Compositing.ForwardRenderer.DrawView(RenderContext context, RenderDrawContext drawContext, Int32 eyeIndex, Int32 eyeCount)
   at Stride.Rendering.Compositing.ForwardRenderer.DrawCore(RenderContext context, RenderDrawContext drawContext)
   at Stride.Rendering.Compositing.SceneRendererBase.Draw(RenderDrawContext context)
   at Stride.Rendering.Compositing.SceneCameraRenderer.DrawInner(RenderDrawContext renderContext)
   at Stride.Rendering.Compositing.EditorTopLevelCompositor.DrawInner(RenderDrawContext context)
   at Stride.Rendering.Compositing.SceneCameraRenderer.DrawCore(RenderContext context, RenderDrawContext drawContext)
   at Stride.Rendering.Compositing.SceneRendererBase.Draw(RenderDrawContext context)
   at Stride.Rendering.Compositing.GraphicsCompositor.DrawCore(RenderDrawContext context)
   at Stride.Rendering.RendererBase.Draw(RenderDrawContext context)
   at Stride.Engine.SceneSystem.Draw(GameTime gameTime)
   at Stride.Games.GameSystemCollection.Draw(GameTime gameTime)
   at Stride.Games.GameBase.Draw(GameTime gameTime)
   at Stride.Editor.EditorGame.Game.EditorServiceGame.Draw(GameTime gameTime)
   at Stride.Games.GameBase.RawTick(TimeSpan elapsedTimePerUpdate, Int32 updateCount, Single drawInterpolationFactor, Boolean drawFrame)
   at Stride.Games.GameBase.RawTickProducer()
   at Stride.Games.GameBase.Tick()
   at Stride.Games.GamePlatform.Tick()
   at Stride.Games.GamePlatform.OnRunCallback()
   at Stride.Games.GameWindowWinforms.<>c__DisplayClass19_0.<Run>b__0()
   at Stride.Games.WindowsMessageLoop.Run(Control form, RenderCallback renderCallback, Boolean useApplicationDoEvents)
   at Stride.Games.GameWindowWinforms.Run()
   at Stride.Games.GamePlatform.Run(GameContext gameContext)
   at Stride.Games.GameBase.Run(GameContext gameContext)
   at Stride.Assets.Presentation.AssetEditors.GameEditor.Services.EditorGameController`1.SceneGameRunThread()
   at Stride.Core.Diagnostics.SafeAction.<>c__DisplayClass1_0.<Wrap>b__0()
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.ThreadHelper.ThreadStart()

AggregateException - InnerExceptions:
  InvalidOperationException: Could not compile shader. See error messages.[(0,0)]: Error:  E1202: The mixin [LuminanceLogShader] in [Mix0] dependency is not in the module

     at Stride.Rendering.EffectSystem.CheckResult(LoggerResult compilerResult)
     at Stride.Rendering.EffectSystem.CreateEffect(String effectName, EffectBytecodeCompilerResult effectBytecodeCompilerResult, CompilerResults compilerResult)
     at Stride.Rendering.EffectSystem.<>c__DisplayClass20_0.<LoadEffect>b__0(Task`1 x)
     at System.Threading.Tasks.ContinuationResultTaskFromResultTask`2.InnerInvoke()
     at System.Threading.Tasks.Task.Execute()

InnerException:
  InvalidOperationException: Could not compile shader. See error messages.[(0,0)]: Error:  E1202: The mixin [LuminanceLogShader] in [Mix0] dependency is not in the module

     at Stride.Rendering.EffectSystem.CheckResult(LoggerResult compilerResult)
     at Stride.Rendering.EffectSystem.CreateEffect(String effectName, EffectBytecodeCompilerResult effectBytecodeCompilerResult, CompilerResults compilerResult)
     at Stride.Rendering.EffectSystem.<>c__DisplayClass20_0.<LoadEffect>b__0(Task`1 x)
     at System.Threading.Tasks.ContinuationResultTaskFromResultTask`2.InnerInvoke()
     at System.Threading.Tasks.Task.Execute()

GPU0.AdapterCompatibility: NVIDIA
GPU0.AdapterDACType: Integrated RAMDAC
GPU0.AdapterRAM: 4293918720
GPU0.Availability: 3
GPU0.Caption: NVIDIA GeForce RTX 2070
GPU0.ConfigManagerErrorCode: 0
GPU0.ConfigManagerUserConfig: False
GPU0.CreationClassName: Win32_VideoController
GPU0.CurrentBitsPerPixel: 32
GPU0.CurrentHorizontalResolution: 1920
GPU0.CurrentNumberOfColors: 4294967296
GPU0.CurrentNumberOfColumns: 0
GPU0.CurrentNumberOfRows: 0
GPU0.CurrentRefreshRate: 59
GPU0.CurrentScanMode: 4
GPU0.CurrentVerticalResolution: 1200
GPU0.Description: NVIDIA GeForce RTX 2070
GPU0.DeviceID: VideoController1
GPU0.DitherType: 0
GPU0.DriverDate: 20210513000000.000000-000
GPU0.DriverVersion: 27.21.14.6647
GPU0.InfFilename: oem13.inf
GPU0.InfSection: Section017
GPU0.InstalledDisplayDrivers: C:\Windows\System32\DriverStore\FileRepository\nvpcdi.inf_amd64_4e518f4648f781be\nvldumdx.dll,C:\Windows\System32\DriverStore\FileRepository\nvpcdi.inf_amd64_4e518f4648f781be\nvldumdx.dll,C:\Windows\System32\DriverStore\FileRepository\nvpcdi.inf_amd64_4e518f4648f781be\nvldumdx.dll,C:\Windows\System32\DriverStore\FileRepository\nvpcdi.inf_amd64_4e518f4648f781be\nvldumdx.dll
GPU0.MaxRefreshRate: 60
GPU0.MinRefreshRate: 59
GPU0.Monochrome: False
GPU0.Name: NVIDIA GeForce RTX 2070
GPU0.PNPDeviceID: PCI\VEN_10DE&DEV_1F10&SUBSYS_152919DA&REV_A1\4&274FFF1B&0&0008
GPU0.Status: OK
GPU0.SystemCreationClassName: Win32_ComputerSystem
GPU0.SystemName: DESKTOP-JOJPGIJ
GPU0.VideoArchitecture: 5
GPU0.VideoMemoryType: 2
GPU0.VideoModeDescription: 1920 x 1200 x 4294967296 colors
GPU0.VideoProcessor: NVIDIA GeForce RTX 2070
Log: 1: Error: Exception in command Build step list (406 items): System.InvalidOperationException: Commands Import stream C:/Users/%USERNAME%/.nuget/packages/stride.rendering/4.0.1.1/stride/Assets/Images/Fog/FogEffect.sdsl > shaders/FogEffect.sdsl and Import stream C:/Users/%USERNAME%/Documents/Stride Projects/SpaceEscape/SpaceEscape.Game/Effects/FogEffect.sdsl > shaders/FogEffect.sdsl are both writing shaders/FogEffect.sdsl at the same time
   at Stride.Core.BuildEngine.ListBuildStep.AddOutputObject(IExecuteContext executeContext, ObjectUrl outputObjectUrl, ObjectId outputObjectId, Command command)
   at Stride.Core.BuildEngine.ListBuildStep.<CompleteCommands>d__18.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.GetResult()
   at Stride.Core.BuildEngine.ListBuildStep.<Execute>d__16.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at Stride.Core.BuildEngine.Builder.<>c__DisplayClass72_2.<<ScheduleBuildStep>b__0>d.MoveNext()
2: Error: BuildStep Build step list (406 items) failed.
3: [(0,0)]: Error:  E1202: The mixin [LuminanceLogShader] in [Mix0] dependency is not in the module
4: [SceneEditorGame]: Error: Unexpected exception. System.AggregateException: One or more errors occurred. ---> System.InvalidOperationException: Could not compile shader. See error messages.[(0,0)]: Error:  E1202: The mixin [LuminanceLogShader] in [Mix0] dependency is not in the module

   at Stride.Rendering.EffectSystem.CheckResult(LoggerResult compilerResult)
   at Stride.Rendering.EffectSystem.CreateEffect(String effectName, EffectBytecodeCompilerResult effectBytecodeCompilerResult, CompilerResults compilerResult)
   at Stride.Rendering.EffectSystem.<>c__DisplayClass20_0.<LoadEffect>b__0(Task`1 x)
   at System.Threading.Tasks.ContinuationResultTaskFromResultTask`2.InnerInvoke()
   at System.Threading.Tasks.Task.Execute()
   --- End of inner exception stack trace ---
   at System.Threading.Tasks.Task`1.GetResultCore(Boolean waitCompletionNotification)
   at Stride.Shaders.Compiler.TaskOrResult`1.WaitForResult()
   at Stride.Rendering.DynamicEffectInstance.ChooseEffect(GraphicsDevice graphicsDevice)
   at Stride.Rendering.EffectInstance.UpdateEffect(GraphicsDevice graphicsDevice)
   at Stride.Rendering.Images.ImageEffectShader.DrawCore(RenderDrawContext context)
   at Stride.Rendering.RendererBase.Draw(RenderDrawContext context)
   at Stride.Rendering.Images.LuminanceEffect.DrawCore(RenderDrawContext context)
   at Stride.Rendering.RendererBase.Draw(RenderDrawContext context)
   at Stride.Rendering.Images.PostProcessingEffects.DrawCore(RenderDrawContext context)
   at Stride.Rendering.RendererBase.Draw(RenderDrawContext context)
   at Stride.Rendering.Images.PostProcessingEffects.Draw(RenderDrawContext drawContext, RenderOutputValidator outputValidator, Texture[] inputs, Texture inputDepthStencil, Texture outputTarget)
   at Stride.Rendering.Compositing.ForwardRenderer.DrawView(RenderContext context, RenderDrawContext drawContext, Int32 eyeIndex, Int32 eyeCount)
   at Stride.Rendering.Compositing.ForwardRenderer.DrawCore(RenderContext context, RenderDrawContext drawContext)
   at Stride.Rendering.Compositing.SceneRendererBase.Draw(RenderDrawContext context)
   at Stride.Rendering.Compositing.SceneCameraRenderer.DrawInner(RenderDrawContext renderContext)
   at Stride.Rendering.Compositing.EditorTopLevelCompositor.DrawInner(RenderDrawContext context)
   at Stride.Rendering.Compositing.SceneCameraRenderer.DrawCore(RenderContext context, RenderDrawContext drawContext)
   at Stride.Rendering.Compositing.SceneRendererBase.Draw(RenderDrawContext context)
   at Stride.Rendering.Compositing.GraphicsCompositor.DrawCore(RenderDrawContext context)
   at Stride.Rendering.RendererBase.Draw(RenderDrawContext context)
   at Stride.Engine.SceneSystem.Draw(GameTime gameTime)
   at Stride.Games.GameSystemCollection.Draw(GameTime gameTime)
   at Stride.Games.GameBase.Draw(GameTime gameTime)
   at Stride.Editor.EditorGame.Game.EditorServiceGame.Draw(GameTime gameTime)
   at Stride.Games.GameBase.RawTick(TimeSpan elapsedTimePerUpdate, Int32 updateCount, Single drawInterpolationFactor, Boolean drawFrame)
   at Stride.Games.GameBase.RawTickProducer()
---> (Inner Exception #0) System.InvalidOperationException: Could not compile shader. See error messages.[(0,0)]: Error:  E1202: The mixin [LuminanceLogShader] in [Mix0] dependency is not in the module

   at Stride.Rendering.EffectSystem.CheckResult(LoggerResult compilerResult)
   at Stride.Rendering.EffectSystem.CreateEffect(String effectName, EffectBytecodeCompilerResult effectBytecodeCompilerResult, CompilerResults compilerResult)
   at Stride.Rendering.EffectSystem.<>c__DisplayClass20_0.<LoadEffect>b__0(Task`1 x)
   at System.Threading.Tasks.ContinuationResultTaskFromResultTask`2.InnerInvoke()
   at System.Threading.Tasks.Task.Execute()<---

5: [SafeAction]: Fatal: Unexpected exception. System.AggregateException: One or more errors occurred. ---> System.InvalidOperationException: Could not compile shader. See error messages.[(0,0)]: Error:  E1202: The mixin [LuminanceLogShader] in [Mix0] dependency is not in the module

   at Stride.Rendering.EffectSystem.CheckResult(LoggerResult compilerResult)
   at Stride.Rendering.EffectSystem.CreateEffect(String effectName, EffectBytecodeCompilerResult effectBytecodeCompilerResult, CompilerResults compilerResult)
   at Stride.Rendering.EffectSystem.<>c__DisplayClass20_0.<LoadEffect>b__0(Task`1 x)
   at System.Threading.Tasks.ContinuationResultTaskFromResultTask`2.InnerInvoke()
   at System.Threading.Tasks.Task.Execute()
   --- End of inner exception stack trace ---
   at System.Threading.Tasks.Task`1.GetResultCore(Boolean waitCompletionNotification)
   at Stride.Shaders.Compiler.TaskOrResult`1.WaitForResult()
   at Stride.Rendering.DynamicEffectInstance.ChooseEffect(GraphicsDevice graphicsDevice)
   at Stride.Rendering.EffectInstance.UpdateEffect(GraphicsDevice graphicsDevice)
   at Stride.Rendering.Images.ImageEffectShader.DrawCore(RenderDrawContext context)
   at Stride.Rendering.RendererBase.Draw(RenderDrawContext context)
   at Stride.Rendering.Images.LuminanceEffect.DrawCore(RenderDrawContext context)
   at Stride.Rendering.RendererBase.Draw(RenderDrawContext context)
   at Stride.Rendering.Images.PostProcessingEffects.DrawCore(RenderDrawContext context)
   at Stride.Rendering.RendererBase.Draw(RenderDrawContext context)
   at Stride.Rendering.Images.PostProcessingEffects.Draw(RenderDrawContext drawContext, RenderOutputValidator outputValidator, Texture[] inputs, Texture inputDepthStencil, Texture outputTarget)
   at Stride.Rendering.Compositing.ForwardRenderer.DrawView(RenderContext context, RenderDrawContext drawContext, Int32 eyeIndex, Int32 eyeCount)
   at Stride.Rendering.Compositing.ForwardRenderer.DrawCore(RenderContext context, RenderDrawContext drawContext)
   at Stride.Rendering.Compositing.SceneRendererBase.Draw(RenderDrawContext context)
   at Stride.Rendering.Compositing.SceneCameraRenderer.DrawInner(RenderDrawContext renderContext)
   at Stride.Rendering.Compositing.EditorTopLevelCompositor.DrawInner(RenderDrawContext context)
   at Stride.Rendering.Compositing.SceneCameraRenderer.DrawCore(RenderContext context, RenderDrawContext drawContext)
   at Stride.Rendering.Compositing.SceneRendererBase.Draw(RenderDrawContext context)
   at Stride.Rendering.Compositing.GraphicsCompositor.DrawCore(RenderDrawContext context)
   at Stride.Rendering.RendererBase.Draw(RenderDrawContext context)
   at Stride.Engine.SceneSystem.Draw(GameTime gameTime)
   at Stride.Games.GameSystemCollection.Draw(GameTime gameTime)
   at Stride.Games.GameBase.Draw(GameTime gameTime)
   at Stride.Editor.EditorGame.Game.EditorServiceGame.Draw(GameTime gameTime)
   at Stride.Games.GameBase.RawTick(TimeSpan elapsedTimePerUpdate, Int32 updateCount, Single drawInterpolationFactor, Boolean drawFrame)
   at Stride.Games.GameBase.RawTickProducer()
   at Stride.Games.GameBase.Tick()
   at Stride.Games.GamePlatform.Tick()
   at Stride.Games.GamePlatform.OnRunCallback()
   at Stride.Games.GameWindowWinforms.<>c__DisplayClass19_0.<Run>b__0()
   at Stride.Games.WindowsMessageLoop.Run(Control form, RenderCallback renderCallback, Boolean useApplicationDoEvents)
   at Stride.Games.GameWindowWinforms.Run()
   at Stride.Games.GamePlatform.Run(GameContext gameContext)
   at Stride.Games.GameBase.Run(GameContext gameContext)
   at Stride.Assets.Presentation.AssetEditors.GameEditor.Services.EditorGameController`1.SceneGameRunThread()
   at Stride.Core.Diagnostics.SafeAction.<>c__DisplayClass1_0.<Wrap>b__0()
---> (Inner Exception #0) System.InvalidOperationException: Could not compile shader. See error messages.[(0,0)]: Error:  E1202: The mixin [LuminanceLogShader] in [Mix0] dependency is not in the module

   at Stride.Rendering.EffectSystem.CheckResult(LoggerResult compilerResult)
   at Stride.Rendering.EffectSystem.CreateEffect(String effectName, EffectBytecodeCompilerResult effectBytecodeCompilerResult, CompilerResults compilerResult)
   at Stride.Rendering.EffectSystem.<>c__DisplayClass20_0.<LoadEffect>b__0(Task`1 x)
   at System.Threading.Tasks.ContinuationResultTaskFromResultTask`2.InnerInvoke()
   at System.Threading.Tasks.Task.Execute()<---


```

**Comment by azeno** [comment]
Applied this PR on master -> GameStudio -> SpaceEscape -> Rename of FogEffect to CustomFogEffect -> works, running on net5.0-windows

**Comment by xen2** [comment]
Let me just run the unit tests again to make sure it's all good

**Comment by xen2** [comment]
It's being built now.
https://teamcity.stride3d.net/buildConfiguration/Engine_Deploy_DeployStride/14338?guest=1

**Pull request merged**
