### PR TITLE
Game Systems to use Services instead of Game object

### PR DESCRIPTION
**Pull request by Basewq**
# PR Details

Bullet2PhysicsSystem and DynamicNavigationMeshSystem to use services to retrieve GameSettings and game systems to remove dependency on Game object.

## Motivation and Context

Ideally Game object should have a 'headless server' mode, but this is a lot of effort.
In the mean time, this change makes it easier to make a "game" class that doesn't inherit the Game class.
eg. consider the following HeadlessGame, but we want to load the physics settings from the asset, or include DynamicNavigationMeshSystem.
https://github.com/xen2/Xenko.ClientServerSample/blob/master/Xenko.ClientServerSample.Server/HeadlessGame.cs

Note I haven't really tested if DynamicNavigationMeshSystem could work in a headless mode, so could be excluded from this commit if it's a bit iffy to change.

## Types of changes

- [ ] Docs change / refactoring / dependency upgrade
- [X] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist

- [ ] My change requires a change to the documentation.
- [ ] I have added tests to cover my changes.
- [ ] All new and existing tests passed.

### CODE REVIEW

**Comment by xen2** [comment]
LGTM!
Did you make sure everything was still working in the Game Studio as well, or should I give it a try?

**Comment by Basewq** [comment]
Yep, opened Game Studio and even created a new project to see if the whole thing runs. Nothing's crashed.

**Comment by slango0513** [comment]
Me too converted the Xenko.ClientServerSample project to stride, and it runs well.
In the current version, it is difficult to implement a headless server. I cannot find a way to add 'Features' like ScriptSystem, pathfinding without refactoring the engine. They always depend more or less on graphics.

**Comment by devjarmo** [comment]
I’ve spent many cycles attempting this. It seems only possible If you implement a custom game base class and use/modify the game tick functionality and then implement a new type of script, script system and a few other items. While I’ve been busy working on other things, my branch has the idea laid out in only new classes if you want to take a look at the concept.

**Comment by slango0513** [comment]
> This reply is re: slango’s headless comment.
> 
> I’ve spent many cycles attempting this. It seems only possible If you implement a custom game base class and use/modify the game tick functionality and then implement a new type of script, script system and a few other items. While I’ve been busy working on other things, my fork has the idea laid out in only new classes if you want to take a look at the concept.

Thank you, I will take a look

**Pull request merged**
