### PR TITLE
Update stride-logo-readme.png

### PR DESCRIPTION
**Pull request by chkworks**
Removes transparent background so it is display correctly in Github page

# PR Details

Really something minor, but still an imporovement over the look of the Github page.

## Description

Just added solid color to the background of the PNG.

## Types of changes

- [x] Docs change / refactoring / dependency upgrade
- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist

- [ ] My change requires a change to the documentation.
- [ ] I have added tests to cover my changes.
- [ ] All new and existing tests passed.

### CODE REVIEW

**Comment by Jklawreszuk** [comment]
Can I ask you what is the reason behind adding new background ? I have a concern that on a light background it might look a bit off.
Please, take a look:
screen

**Comment by chkworks** [comment]
Okay... well, in my case it looks like this:

Bildschirmfoto 2023-01-18 um 15 58 09

**Comment by chkworks** [comment]
I added a bit of padding to the image, so now its not that misplaced. Also I obviously had to choose between dark on white background or white on dark background, and thought the version white on dark works for both backgrounds a bit better. Hope it also works for you guys.

Bildschirmfoto 2023-01-18 um 16 22 46
Bildschirmfoto 2023-01-18 um 16 22 52

**Comment by Jklawreszuk** [comment]
I still think there is a better solution for supporting dark themes. Maybe instead of adding an unnecessary background, we could just add an outline to the logo in a similar way Godot does?

Reference (dark/light theme) : 
comparsion
What do you think?

**Comment by chkworks** [comment]
Good call! I added an outer glow to the logo, that worked better than an outline IMO.

**Comment by manio143** [comment]
Currently this is what I see on your branch:
image
While I guess it could make sense to add some border to make the logo more visible in dark themed GitHub, IMO it should be minimal - (2-3px) - the glow I see looks very thick on the dark version and because it's feathered it makes the text less readable. I think a hard edge or much less intense feathering would be preferred.

But actually, I see there's a way to use different image for different theme color - https://github.com/GiorgosXou/Random-stuff/tree/main/Programming/StackOverflow/Answers/70200610_11465149
As such it would be advisable to use the correct logos. I pulled this zip of SVGs from Discord (author sebl):
[stridesvgs.zip](https://github.com/stride3d/stride/files/10776844/stridesvgs.zip)
We should use the SVGs to generate the PNGs without loss of quality. The current one is `solid.svg`, the white one is `solid-1.svg`

**Comment by chkworks** [comment]
Okay, that seems to be a good way to go.

I have pushed the black and white versions made from sebls SVGs. What I don't know is how to link them properly, right now the path seems to be set dynamically but in the example a direct path is used. Could you link them in the Readme?

**Comment by Jklawreszuk** [comment]
@chkworks Well, I think its a matter of choice. I would rather go with direct path because, less megs would be downloaded :v:

**Comment by chkworks** [comment]
Alright, I have reverted the original logo to the design without the outer glow, but left the black and white versions in this PR. When they are pushed into the main branch, I can try to include them with the provided method using direct paths to the versions, depending on the theme.

**Comment by Jklawreszuk** [comment]
> When they are pushed into the main branch, I can try to include them

@chkworks Why not directly in your current PR?

**Comment by chkworks** [comment]
Alright, I initially thought that the URL will be linked to my user name, but I think the path is now taken from the original repository... hope that works now?

**Comment by Jklawreszuk** [comment]
Yes it does! Looks good to me.

**Review by Jklawreszuk — APPROVED** [review]

**Pull request merged**
