### PR TITLE
feat: Port predicates.c to .NET

### PR DESCRIPTION
**Pull request by Jklawreszuk**
# PR Details

My PR ports `predicates.c` logic used in BowyerWatsonTetrahedralization.cs in Stride.Rendering module.
For sake of our usage,  I decided to port the functions that are actually used in the Engine thus reducing the number from ~ 4k lines of code to 1.5k.

## Related Issue

#1394 

## Types of changes

- [x] Docs change / refactoring / dependency upgrade
- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist

- [ ] My change requires a change to the documentation.
- [ ] I have added tests to cover my changes.
- [ ] All new and existing tests passed.
- [x] **I have built and run the editor to try this change out.**

### CODE REVIEW

**Comment by VaclavElias** [comment]
mpressive that some dependencies can be sorted with just a snap of the fingers 🙂.

**Comment by Jklawreszuk** [comment]
I think, this is the last one that requires less effort. Now only the difficult ones remain 😆

**Comment by Jklawreszuk** [comment]
Cool, It seems to work 💪

image

**Comment by Eideren** [comment]
Thanks !

**Pull request merged**
