### PR TITLE
Remove docs, has been moved to Stride docs repo

### PR DESCRIPTION
**Pull request by Aggror**
# PR Details
The docs folder in the Stride folder has been moved to the official Stride 3d repo and can be seen published here:
https://doc.stride3d.net/latest/en/contributors/engine/architecture/index.html

1 file that needs to be reviewed before moving to Official Stride docs is Copy-paste.md 

## Motivation and Context
Keeping all docs in 1 place as much as possible.

## Types of changes
- [ x] Docs change / refactoring / dependency upgrade
- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist
- [x ] My change requires a change to the documentation.
- [ ] I have added tests to cover my changes.
- [ ] All new and existing tests passed.
- [ ] **I have built and run the editor to try this change out.**

### CODE REVIEW

**Comment by Eideren** [comment]
What's the issue with `Copy-paste.md` exactly, not sure what I should review ? We could move it to the website and review it over there instead ?

**Comment by VaclavElias** [comment]
This one https://github.com/stride3d/stride/blob/master/docs/technical/copy-paste.md

**Comment by Eideren** [comment]
Sure, but what's the issue exactly ?

**Comment by VaclavElias** [comment]
Is the content relevant in that file,do we need it, and where it should be moved to our Stride Docs.

**Comment by Eideren** [comment]
Yep, in architecture next to the rest of them https://doc.stride3d.net/latest/en/contributors/engine/architecture/index.html

**Comment by VaclavElias** [comment]
Hey @Aggror, I moved `copy-paste.md` here https://github.com/stride3d/stride-docs/blob/master/en/contributors/engine/architecture/copy-paste.md

Please, double, triple check if you would like this PR being merged, so we don't lose removed content.

**Comment by Aggror** [comment]
@VaclavElias With that file moved, we can go ahead and remove this folder. 
Everything should reside in the docs contributor section now.

**Pull request merged**
