### PR TITLE
feat: Adjust DirectXTex wrapper for all platforms

### PR DESCRIPTION
**Pull request by Jklawreszuk**
# PR Details

This PR adds a Linux DxtWrapper binary file for Linux and a simple cmake script to replicate on other platforms . Additionally , my wrapper is based on the latest version of DirectXTex thanks to vcpkg - package manager for c++. I also added UTC32StringMarshaller because there is no support for Wide character on Linux.

- [ ] - My change requires testing on Windows and if that is required,, update Windows shared library too.

## Types of changes

- [ ] Docs change / refactoring / dependency upgrade
- [x] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [x] Breaking change (maybe?)

## Checklist

- [ ] My change requires a change to the documentation.
- [ ] I have added tests to cover my changes.
- [ ] All new and existing tests passed.
- [ ] **I have built and run the editor to try this change out.**

### CODE REVIEW

**Comment by Jklawreszuk** [comment]
Note: PR https://github.com/stride3d/stride/pull/2303 needs to be merged first

**Comment by Eideren** [comment]
Was about to start TC on this PR but you probably want to pull from master given you mentioned #2303 needs to be merged first ?

**Comment by Jklawreszuk** [comment]
@Eideren Correct! I rebased my branch now, so it should be ready for testing 👀

**Comment by Eideren** [comment]
Everything works as expected, thanks again @Jklawreszuk !

**Pull request merged**
