### PR TITLE
Vulkan Fullscreen Fix

### PR DESCRIPTION
**Pull request by tamamutu**
# PR Details
Fix Stride projects using the Vulkan backend to properly support fullscreen.

## Description
Enabling swapchain recreation in SwapChainGraphicsPresenter.Vulkan.cs so that changes in resolution at runtime don't stop the game from rendering to the screen.

## Related Issue
#1024

## Motivation and Context
Makes window creation more convenient to the end user and makes window behavior consistent across graphics backends.

## Types of changes

- [ ] Docs change / refactoring / dependency upgrade
- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist

- [ ] My change requires a change to the documentation.
- [ ] I have added tests to cover my changes.
- [x] All new and existing tests passed.

### CODE REVIEW

**Comment by NicusorN5** [comment]
Shouldn't you mark this as a bug fix in the "types of changes"?

**Comment by Eideren** [comment]
That's fine, we can infer it from the title, and the pr description is likely wip as well

**Comment by tamamutu** [comment]
Update: Issue seems to be that the Vulkan backend doesn't handle swapchain recreation and instead just sets the backbuffer to the screen resolution and renders to the visible window area. When going fullscreen at a resolution different to the screen's current resolution, swapchain recreation is needed, but since the renderer doesn't handle it, the program just breaks and nothing is rendered to the screen. From what I can tell, resizing works just fine if you call OnRecreated() in the Present() method of SwapchainGraphicsPresenter when Vulkan reports that the swapchain is out of date. I'll add some commits to this PR in a sec just so I can make sure this fix doesn't only work on my end.

**Comment by Eideren** [comment]
@tamamutu great, let me know if/when you want me to try it out

**Comment by tamamutu** [comment]
I'd really appreciate it if you could try and get it working on your end, if anything weird comes up or there's any issues with it just let me know and I'll see if I can debug it.

**Comment by Eideren** [comment]
Yep, works as expected, remove the wip whenever you're ready and I'll merge it in.
Just a note for other users, Vulkan can't really be built with this PR as is, it was broken in #1654 and will be fixed in #1697 - you would need to either pull from before pr 1654 or cherry pick what's missing.

**Comment by tamamutu** [comment]
Sweet as, the PR should be good to go now.

**Pull request merged**
