### PR TITLE
Update setup packages to detect and install .NET 6

### LINKED ISSUE #1410: StrideSetup.exe needs to be updated
**Release Type**: GitHub

**Version**: master

The current setup requires .NET 4.7.2 rather than .NET 6.  The setup.aip needs to be updated to require and download .NET 6.

We should probably also limit the supported OSes to Windows 10, 11 and Server 2019 and 2022.

### PR DESCRIPTION
**Pull request by jrinker03**
# PR Details
Update the setup prereqs and main setup installer projects to detect and, if needed, install .NET 6.   At the moment Advanced Installer only knows about 6.0.2 but that will be fine.

Also update to latest Advanced Installer, version 19.4.

## Related Issue
Fixes #1410 

- [ ] Docs change / refactoring / dependency upgrade
- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist
Manually tested.

- [ ] My change requires a change to the documentation.
- [ ] I have added tests to cover my changes.
- [ ] All new and existing tests passed.

### CODE REVIEW

**Comment by jrinker03** [comment]
@Xen2 is updating the build server to use AI 19.4 as well.

**Comment by jrinker03** [comment]
Note that the Advanced Installer GUI made all these changes, and I can't claim to know the exact effect of each one.  Manual testing of a locally built setup does show it works as expected.   Once Xen2 gets the build server updated, I'll run a build and test from an official build as well.

**Comment by manio143** [comment]
I looked through this XML and I think it's ok (lots of installer specific stuff) - so long as we can run it in a VM from a clean Windows installation and get to run Stride that's all we need.
I remember there being another requirement for VCRedist to run GameStudio, so maybe we could add that as well?

**Comment by jrinker03** [comment]
>I remember there being another requirement for VCRedist to run GameStudio, so maybe we could add that as well?

While I'm sure that's so, it's missing from the [prereqs web page](https://doc.stride3d.net/latest/en/manual/requirements/index.html).   

Win 10+ comes with the Universal CRT so it shouldn't be an issue, it's only for older OSes that this might come into play.
And interestingly Advanced Installer doesn't even list a CRT as an option it supports out-of-the box.  

If needed, perhaps we should just add it later since it hasn't been in these projects previously?

**Comment by jrinker03** [comment]
>so long as we can run it in a VM from a clean Windows installation and get to run Stride that's all we need.

I've verified a locally built installer EXE on a clean VM (win10-21h2-pro) and it works as expected:  it detects that .NET FW 4.x is installed and that .NET6  is not.  It properly downloads and installs the missing prereq and then properly installs the Launcher.    The Launcher is started at the completion of setup and works as expected.

I'll re-run on a new clean VM with a StrideSetup.exe from the build server once this PR is accepted and a build run.

**Comment by jrinker03** [comment]
@manio143 - any objection with moving forward with the PR as-is since it seems to behave as expected?

**Comment by manio143** [comment]
None from me. Not sure if we're waiting on @xen2 to comment before merging?

**Comment by jrinker03** [comment]
OK, thanks.

Xen2 has the link to this PR so not sure.

**Comment by xen2** [comment]
There's also sources/prerequisites/prerequisites.aip for Stride itself
Supposedly launcher should have installed it, but I think it's still good to add it there in case the launcher has different requirements in the future (and it doesn't install .NET 6, for example if we pack launcher with .NET 6 runtime).

**Comment by xen2** [comment]
Thinking about it, we need to check if launcher already published with self-contained .NET 5/6 runtime.
If yes, both launcher setup don't need .NET 6.0, only Stride itself.

**Comment by jrinker03** [comment]
Pushed the latest based on clean VM testing.  In the end:
- As @xen2 was thinking, since the launcher is a self-contained EXE, there is no need for a .NET 6 prereq.  I've removed that.
- I've updated the Stride prereq installer and on a Win10 21h2 machine it successfully evaluates everything and discovers that everything is good-to-go (CRT, DirectX and .NET dependencies) and exits without doing anything else.   This was verified with event log entries.

In the end, the update is really to use 19.4 version of Advanced installer and to change the Stride prereq installer to look for .NET 6 instead of 5.

**Comment by jrinker03** [comment]
As an interesting aside, the Azure OS image comes with .NET 6 MSI in the OSes package cache, so it didn't wind up downloading it, just installing.

**Comment by jrinker03** [comment]
Ah, and same with the CRT, it turns out.   Since it was a very fast silent install it tricked me into thinking it didn't do anything.

It might be worth considering moving to the Universal CRT but we can save that for another day since this works.

**Comment by Eideren** [comment]
Sounds like this PR is good to go, ready to merge ?

**Review by manio143 — APPROVED** [review]

**Pull request merged**
