### PR TITLE
[Graphics] Fix expected image size for OpenGL textures.

### PR DESCRIPTION
**Pull request by Basewq**
# PR Details

Fixes "Image size different than expected." in the Asset Compiler when compiling for Android with graphics level 10+.

## Description

Gets the correct 'bpb' value for certain ETC2 pixel formats.

## Related Issue

Solves the first part of #1600 however my machine isn't set up correctly to fix the other ETC2 issues.

## Types of changes

- [ ] Docs change / refactoring / dependency upgrade
- [X] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist

- [ ] My change requires a change to the documentation.
- [ ] I have added tests to cover my changes.
- [ ] All new and existing tests passed.

### CODE REVIEW

**Comment by Eideren** [comment]
Thanks a bunch @Basewq !
There are a couple of extraneous white spaces included with your commit, not a big deal at all, but try to avoid including them if you can :)

Seems fairly straightforward, I'll merge this in.

**Comment by Basewq** [comment]
> Thanks a bunch @Basewq ! There are a couple of extraneous white spaces included with your commit, not a big deal at all, but try to avoid including them if you can :)
> 
> Seems fairly straightforward, I'll merge this in.

Thanks, strangely enough I don't see those extraneous whitespaces changes in git on my machine (or in the commits itself on my machine). It seems github might be doing some extra work?

**Comment by Eideren** [comment]
Couldn't tell you why that is, perhaps your git diff or the tool you use to see diffs doesn't display whitespace changes.
It's fine if you can't figure it out, we'll merge those if their benign and remove them through github's text editor if not.

**Comment by Basewq** [comment]
> Couldn't tell you why that is, perhaps your git diff or the tool you use to see diffs doesn't display whitespace changes. It's fine if you can't figure it out, we'll merge those if they are benign and remove them through github's text editor if not.

Oops, you're right, at some point I accidentally clicked a setting to hide whitespace only changes and didn't notice. Thanks for pointing it out!

**Comment by Eideren** [comment]
Nice, glad we could figure this one out !

**Pull request merged**
