### PR TITLE
feat: System.Numerics Conversions

### PR DESCRIPTION
**Pull request by Eideren**
# PR Details
Investigating whether we can cherry pick #1161 now that we've aligned the frameworks - stems from the discussion in #2238.
PR done to run this stuff on TC, work will likely continue in #2238 instead.

## Related Issue
None.

## Types of changes
- [ ] Docs change / refactoring / dependency upgrade
- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist
- [ ] My change requires a change to the documentation.
- [ ] I have added tests to cover my changes.
- [ ] All new and existing tests passed.
- [ ] **I have built and run the editor to try this change out.**

### CODE REVIEW

**Comment by Eideren** [comment]
Not sure why it's breaking and I am not on my dev machine, feel free to investigate further @Doprez if you want to - I'll look into it again next month otherwise

**Comment by Doprez** [comment]
I can probably find time next week or this weekend. Most people are taking vacations after this week so I should be getting a lot less requests hopefully until January lol.

Do you have that Discord discussion mentioned in the other PR available by any chance?

**Comment by Doprez** [comment]
https://discord.com/channels/500285081265635328/500290856532574209/897483805470908436 got it! Just in case there is some useful info mentioned there.

**Comment by Doprez** [comment]
Ok so it seems like the issue was just the .NET version at the time.
image

https://www.nuget.org/packages/system.numerics.vectors/#supportedframeworks-body-tab
maybe we were one year too early? Ill see if I can figure out getting the mobile builds working in 4.2 this weekend.

The team city builds are complaining about signing certs which I think is unrelated to this issue.

**Comment by Doprez** [comment]
I cant even get the android source to build normally in master. maybe @MeharDT or @Basewq  can help test this?

The errors Im getting are just about it referencing the wrong dll files:
```
XA4301: Cannot determine ABI of native library '..\.nuget\packages\stride.virtualreality\4.2.0.1\lib\net8.0\runtimes\win-x64\native\openvr_api.dll'. Move this file to a directory with a valid Android ABI name such as 'libs/armeabi-v7a/'.
```

I mean, the good news is the project at least builds but as soon as I try to run it it fails. So I dont think this error has anything to do with the implicit conversions like it did in the past.

I followed the instructions to build by deleting the nugets fully and rebuilding from the Stride.Android.sln but it still throws the above error.

references for trying to get android to build:
https://discord.com/channels/500285081265635328/1152588396288544819/1297511423886360658
https://discord.com/channels/500285081265635328/1152588396288544819/1306469216945176607
https://github.com/stride3d/stride/discussions/1657

**Comment by Eideren** [comment]
TC's simple test breaks on this one, so might just be a random issue with this particular branch, you can add the explicit conversion on your branch and I'll try running TC over it

**Comment by Basewq** [comment]
> I cant even get the android source to build normally in master. maybe @MeharDT or @Basewq can help test this?
> 
> The errors Im getting are just about it referencing the wrong dll files:
> 
> ```
> XA4301: Cannot determine ABI of native library '..\.nuget\packages\stride.virtualreality\4.2.0.1\lib\net8.0\runtimes\win-x64\native\openvr_api.dll'. Move this file to a directory with a valid Android ABI name such as 'libs/armeabi-v7a/'.
> ```
> 
> I mean, the good news is the project at least builds but as soon as I try to run it it fails. So I dont think this error has anything to do with the implicit conversions like it did in the past.
> 
> I followed the instructions to build by deleting the nugets fully and rebuilding from the Stride.Android.sln but it still throws the above error.
> 
> references for trying to get android to build: https://discord.com/channels/500285081265635328/1152588396288544819/1297511423886360658 https://discord.com/channels/500285081265635328/1152588396288544819/1306469216945176607 #1657

Sorry for the late reply, I'm not 100% sure why the Android build isn't working for you. Most likely after building the Android solution you somehow rebuilt the 'standard'/Windows one and that overwrites the nuget.
I know that the teamcity has a more special setup that allows for properly building all variants, but trying to manually build Android is very finicky.

**Comment by Doprez** [comment]
You are probably right about the nuget overwriting, I was trying to do it properly but it definitely was very finicky. Not a huge issue though, the thing I was worried about seemed to be resolved in the .NET updates including `Numerics` in the packages.

**Pull request closed without merging**
