### PR TITLE
Avalonia Launcher rewrite

### PR DESCRIPTION
**Pull request by Kryptos-FR**
# PR Details

This PR contains the initial work on a porting the Launcher to [Avalonia](https://github.com/AvaloniaUI/Avalonia) .

It is based on #2082, which can either be reviewed/merged separately or directly with this PR.

## Related Issue

- #2034
- #2082

## Motivation and Context

Part of the effort to transition from WPF/Winforms to Avalonia, though it doesn't directly depend on #2034.

## Types of changes

- [ ] Docs change / refactoring / dependency upgrade
- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist

- [x] My change requires a change to the documentation.
  - Need to rewrite the doc of the Launcher has some prerequisites might have changed. And the visuals are slightly altered. 
- [ ] I have added tests to cover my changes.
- [ ] All new and existing tests passed.
- [x] **I have built and run the launcher to try this change out.**

### CODE REVIEW

**Comment by Kryptos-FR** [comment]
Merging into `xplat-editor`. If we want to have it for a future official release (and before the whole GameStudio Avalonia port is done), we can just merge that branch again into `master`.

**Comment by xen2** [comment]
Nice job! I tried it and it seems to work well.
Wrote down a few minor cosmetic details (but we can improve on that later, no need to do that now -- I suppose your focus was more on the port itself).
image

Again, great work :)

**Comment by xen2** [comment]
Also, I am curious, how is your experience with Avalonia so far? is it going smoothly, not too many (unexpected) issues?
No specific blockers on the viewmodel side, quantum, stride itself, etc.?

**Comment by Kryptos-FR** [comment]
> Wrote down a few minor cosmetic details for later (but we can improve on that in a second pass later, no need to do that now -- I suppose your focus was more on the port itself than this kind of smaller details).

Good catch. I indeed didn't focus much on visuals, but I think those can be fixed easily. The center alignment issue seems to be a styling difference between Avalonia and WPF though, I'll double check.

> Again, great work :)

Thanks :)

> Also, I am curious, how is your experience with Avalonia so far? is it going smoothly, not too many (unexpected) issues?
No specific blockers on the viewmodel side, quantum, stride itself, etc.?

It's rather smooth. Existing view models work almost as-is, which means I will be able to have at some point both WPF and Avalonia versions side-by-side sharing the same view models. That way, it will be easier to compare and fix any difference in behavior. On the view side, there are a couple of difference in term of how styling works, but the control have for the most part the same name and the same properties. I was pleased to be able to rewrite our own value converters without much trouble (incl. the ability to chain them inline as we are doing in the GameStudio).

**Pull request merged**
