### PR TITLE
Interfaces IGame, IGameBase

### PR DESCRIPTION
**Pull request by CharlesWoodhill**
# PR Details
Issue: #999

Renamed and enriched Interface from IGame to IBaseGame
Created Interface: IGameBaseInternal (to cover internal marked props/methods)
Created Interface: IGame
Let Game implement IGame
Let GameBase implement IGameBase (implicit) and IGameBaseInternal (explicit)
Replaced most uses of GameBase to IGameBase (where appropriate)
Replaced most uses of Game to IGame (where appropriate)

## ATTENTION

i only tested my changes with windows and there with PlatformDesktop
but the change needed to edit source encapsulated in compiler directives
so i can only hope i did everthing right.

Can anybody compile and test this for me on other platform(s)?

## Motivation and Context

More control from "Outside" when using Stride as library.

## Types of changes

- [ ] Docs change / refactoring / dependency upgrade
- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [x] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist

- [ ] My change requires a change to the documentation.
- [ ] I have added tests to cover my changes.
- [ ] All new and existing tests passed.

### CODE REVIEW

**Comment by manio143** [comment]
Can you check if this change has any impact on performance? Virtual calls for interfaces are ever so slightly [more expensive](https://stackoverflow.com/questions/7225205/performance-of-direct-virtual-call-vs-interface-call-in-c-sharp) but I'm not sure if `Game` methods are called often enough for it to matter.

**Comment by Eideren** [comment]
@manio143 the large majority of functions within 'game' are called once at most per frame, perf hit won't be meaningful here

@CharlesWoodhill 
Could you give an example where this is necessary ? 
With this PR we'll have ``IGameBase``, ``GameBase``, ``IGame`` and ``Game``, it's kind of getting ridiculous, I would rather we had a single class which just contains virtual properties and functions to be overridden by users instead of this mess of obtuse types.

Could you verify that all of the changes you included are actually necessary ?
``sources/engine/Stride.Engine/Engine/Sim.cs `` is commented out but still included with this PR, 
``sources/targets/Stride.Core.TargetFrameworks.Editor.props``'s changes lay outside the scope of this PR.

Should ``sources/engine/Stride.Games/SimBase.cs`` really be included in this PR if, according to the comment, it is still experimental, probably needs a better name if that's the case, like ``GameCodeOnly`` / ``MinimalGame``, something more obvious.

**Comment by CharlesWoodhill** [comment]
I did this to be able to create a more "open" Game object (working tiltle Sim object)
without tampering with exitsting Game object.
The Sim object should be targeting users who use Stride from their existing project
things it should be able to do:
provide a feature to use "external" log,
provide a feature to run on other thread than mainthread  (the main thread is owned by the user not the engine)
provide a feature to use "external" window as "mainWindow"
more to come :)

**Comment by Eideren** [comment]
I don't think it's smart to just go ahead and implement another ``Game`` every time we have a specific setup to cover, that's one more class we'll have to maintain every time we make changes to games and you'll never have an implementation that would satisfy all users, so the smartest way to go about this is:
- Either you have to make it incredibly basic and provide documentation for users to build it up however they want, i.e. ``game`` now is just an interface, users will deal with the implementation on their side but you expose functions to help them build it up.
- Or you make it complete and extensible enough so that most users don't have to fiddle with it but those who do, can change it however they want.

I would rather you go with the later, see what you need to change to make ``Game`` or ``GameBase`` work with your setup and expose/branch/decouple them.

---

> provide a feature to use "external" log,

Afaik you can already do that, not sure what you mean otherwise.

> provide a feature to run on other thread than mainthread (the main thread is owned by the user not the engine)

``Game`` uses the thread you ``Run()`` it on, perhaps under certain windowing system that's not the case ? Feel free to correct me.

> provide a feature to use "external" window as "mainWindow"

Yes, that would require some changes to the engine but can still be used from a standard ``Game`` instance, like when we use ``Run(someWindowingSystem)``, this parameter could be changed to something more abstract.

---

I really think that you need to make changes to this pr before we can merge it, Xen can do so if he wants to but I don't agree with a lot of those changes.
- Rollback changes to ``sources/targets/Stride.Core.TargetFrameworks.Editor.props``, it's out of scope and I would rather Xen deal with these kinds of changes.
- Remove unnecessary / logic commented out.
- ``IGame.AutoLoadDefaultSettings`` this member should be specified through a constructor, not an interface member, why should all implementations of ``IGame`` implement this ?
- Change how you implement this, see the first section of this message.

**Comment by CharlesWoodhill** [comment]
maybe it was too fast, better close it unmerged

**Comment by Eideren** [comment]
@CharlesWoodhill please, don't be discouraged by what I told you. You've got the right idea, 'just needs a little more work on your side before I merge this in.

**Comment by CharlesWoodhill** [comment]
nono you are right, it was too fast

**Pull request closed without merging**
