### PR TITLE
Xml comments fixing 1

### PR DESCRIPTION
**Pull request by VaclavElias**
# PR Details

This PR is fixing numerous XML Comments issues reported by DocFX, our Stride Docs API generator.

## Description

- Mostly incorrect `cref` corrected which couldn't be resolved for various reasons like typos, missing namespace, private methods.
- Some typos fixed along the way

These corrections will make links in Stride Docs working, or removing the link if the entity is not available for public access.

## Related Issue

https://github.com/stride3d/stride/issues/1681

## Motivation and Context

Stride Docs improvements.

## Types of changes

- [x] Docs change / refactoring / dependency upgrade
- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist

- [ ] My change requires a change to the documentation.
- [ ] I have added tests to cover my changes.
- [ ] All new and existing tests passed.

### CODE REVIEW

**Comment by tebjan** [comment]
Awesome, we just have to check whether this has a conflict with any PR in the queue...

**Comment by VaclavElias** [comment]
No problem, so I shall wait with other PRs on the same subject, there is around 150 issues left? 🤣

**Comment by VaclavElias** [comment]
@tebjan, which PRs should I check if I have a conflict with?

**Comment by VaclavElias** [comment]
I fixed a conflict in this PR.

**Comment by Eideren** [comment]
Thanks !

**Pull request merged**
