### PR TITLE
Register assemblies in the assembly container to ensure later assembly loads succeed

### PR DESCRIPTION
**Pull request by azeno**
# PR Details

## Description

Different approach to what I proposed in https://github.com/stride3d/stride/pull/965. This time all the dependencies as given by the project are registered in the used assembly container to ensure that a later assembly load will work.

## Related Issue

https://github.com/stride3d/stride/pull/965

## Types of changes

- [ ] Docs change / refactoring / dependency upgrade
- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist

- [ ] My change requires a change to the documentation.
- [ ] I have added tests to cover my changes.
- [x] All new and existing tests passed.

### CODE REVIEW

**Comment by xen2** [comment]
Does it run `AssemblyContainer.CurrentDomain_AssemblyResolve` before throwing the exception? (with a not-null `container`)
If yes, I think it might be better to do the few required assembly-loads lazily in there rather than forcing all of them to load.

However, I am not sure why we don't do that for the `.deps.json` case already. Maybe it doesn't work in practice.

Do you happen to have a repro project so that I could quickly test?

**Comment by azeno** [comment]
1) Checkout `dev/azeno/assembly-load-repro` of https://github.com/vvvv/VL.Stride/tree/dev/azeno/assembly-load-repro and build the `packages/VL.Stride.Runtime` project (if you build the whole solution it will try to install vvvv which you don't need). You should end up with VL.Stride.* packages in `LocalAppData\Stride\Nuget Dev`
2) Download and build this console app: 
[ConsoleApp1.zip](https://github.com/stride3d/stride/files/5729454/ConsoleApp1.zip)

The build step should crash with a type load exception.

**Comment by azeno** [comment]
Oh and the assemblies are not force loaded - just their paths get registered in case they need to be loaded.

**Comment by xen2** [comment]
Sorry, I misread the code and thought `LoadAssemblyByName` was called by another top-level function rather than `AssemblyResolve`.
So it's already doing what I was describing, thanks 👍

**Pull request merged**
