### PR TITLE
Audio emitter multiple references to same asset bugfix

### PR DESCRIPTION
**Pull request by ComputerSmoke**
This fixes the bug where changing the parent of an entity with an audio emitter component referencing the same sound asset multiple times would cause a crash.

# PR Details

Previously when the parent of such an entity was changed, there would be a crash because detach would be called on the same SoundBase object for each corresponding key in Sounds. Now, when an entry is removed from Sounds in AudioEmitterComponent, the corresponding SoundBase is only detached if there are no other keys referencing it in Sounds.

## Description

This is accomplished by maintaining a dictionary mapping each SoundBase to its set of keys in Sounds, and only detaching a SoundBase when its set of Sound keys is empty. This implementation still keeps just one AudioEmitterSoundController per SoundBase.

## Related Issue

https://github.com/stride3d/stride/issues/2024

## Motivation and Context

Users may occasionally want the same sound asset to have multiple references from the same audio emitter (especially during early game development), so Stride should allow it instead of crashing unexpectedly when a parent of the object is set during runtime.

## Types of changes

- [ ] Docs change / refactoring / dependency upgrade
- [ x ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist

- [ ] My change requires a change to the documentation.
- [ ] I have added tests to cover my changes.
- [ ] All new and existing tests passed.
- [ x ] **I have built and run the editor to try this change out.**

### CODE REVIEW

**Comment by Eideren** [comment]
Looks good, thanks again @ComputerSmoke ! Just a small question, it looks like you've used a hashset purposefully here, can you quickly go over why that is compared to a `Dictionary<SoundBase, int>` which would be incremented on add and decremented on remove regardless of the key, and would call detach when zero ?
I can see the behavior of both differing when the same key and sound is used multiple times.

One minor nitpick would be to remove the key after detaching;
```cs
if (SoundKeys[sound].Count == 0)
{
   DetachSound(sound);
   SoundKeys.Remove(sound);
}
```

**Comment by ComputerSmoke** [comment]
@Eideren I thought it was possible for the same key / sound to have two Add events in a row, but on investigating this I see that it is not (setting an existing key calls Remove before Add, and you can't call Add on a key that is already in the set). Counting instead of keeping track of each key should therefore have the same effect as the hash set, so I've changed the implementation to use the counting method you described.

I've also added that key removal for 0 values.

**Comment by Kryptos-FR** [comment]
Wondering if that needs thread-safety guarantees (for instance using a lock). Can this code be called from multiple threads or are all sound-related logic always executed from the same (main?) thread?

**Comment by ComputerSmoke** [comment]
The user could modify Sounds from any thread, but since it's a TrackingDictionary (which isn't thread safe since it's backed by a Dictionary), so anything modifying it in the current code must already be responsible for avoiding concurrent changes to Sounds.

The other place where this code is called is AttachToProcessor and DetachFromProcessor, but both call the Attach and Detach methods which can modify SoundToController, another Dictionary. 

Assuming Attach/Detach for components doesn't collide, the case where something might go wrong is if user code modifies Sounds or calls Attach/Detach while AttachToProcessor is being called. I don't know if such a situation is possible, but if it is then it should be equally unsafe with and without these changes.

Not that we shouldn't add thread safety to anything, but there might already be some more generally implemented for this sort of thing?

**Comment by Eideren** [comment]
Yep it would be nice, but adding thread safety in would be out of scope for this PR I would think, thanks again @ComputerSmoke !

**Pull request merged**
