### PR TITLE
[Games] Improvements on SDL and GameWindow

### PR DESCRIPTION
**Pull request by tebjan**
# PR Details
* Renamed GameContextWindows to GameContextDesktop
* Added IsUserManagingRun to all desktop platforms
* Added IsFullscreen, PreferredWindowedSize and PreferredFullscreenSize for easy fullscreen mode switch
* Added ALT+ENTER fullscreen toggle to SDL window (same behavior as on winforms)
* Fixed first mouse click on SDL window not passing through
* Fixed SDL FullscreenToggle not remembering the previous windowed state
* Fixed SDL `BringToFront()`

## Description

Several improvements on SDL, for example, no more screen blackout when switching to fullscreen by doing the resize and window state change in the right order.

I also added new properties to the general `GameWindow` class to allow a more easy workflow of switching between windowed and fullscreen mode, e.g.:

    game.Window.PreferredFullscreenSize = new Int2(1920, 1080);
    game.Window.IsFullscreen = true;

## Motivation and Context

More easy and fluent workflow with SDL and `GameWindow`.

## Types of changes

- [ ] Docs change / refactoring / dependency upgrade
- [x] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist

- [x] My change requires a change to the documentation.
- [ ] I have added tests to cover my changes.
- [ ] All new and existing tests passed.

### CODE REVIEW

**Comment by Eideren** [comment]
Fixes #733 
At least according to the description

**Comment by tebjan** [comment]
@Eideren if it is related to the first click when the window gets focused by the click itself. it is better described here: https://discourse.libsdl.org/t/sdl2-on-focus-gain-first-click-detection/23185

Maybe try the branch and see whether it gets fixed. do you even have the possibility to try the game on macOS or Linux?

**Comment by Eideren** [comment]
@tebjan Right now I don't have anything easy setup to test on linux or mac so I can't really test those out, I'll test it tomorrow on windows though.

**Comment by Eideren** [comment]
The particular issue I had was unrelated.
Tested this PR and it works as expected, fullscreen has some weird rendering issues and sometimes throws in specific situations but I already had those before this PR.

**Comment by tebjan** [comment]
Thanks for testing!

**Pull request merged**
