### PR TITLE
fix: Xml Comments - Update 4

### PR DESCRIPTION
**Pull request by VaclavElias**
# PR Details

This PR is fixing numerous XML comments issues, around 60.

## Description

- Fixing typos
- Fixing `cref` references
- Removing `cref` references for unknown, none existing references

Note that some references are not working because we have the same namespaces in different assemblies and then some references are not working unfortunatelly, such `cref` was removed.

Once merged, these updates will be automatically applied to Stride API in the next Stride Docs release.

## Related Issue

https://github.com/stride3d/stride/issues/1681

## Motivation and Context

This xml comments are rendered in our Stride Docs and ideally they should work.

## Types of changes

- [x] Docs change / refactoring / dependency upgrade
- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist

- [x] My change requires a change to the documentation.
- [ ] I have added tests to cover my changes.
- [ ] All new and existing tests passed.
- [x] **I have built and run the editor to try this change out.**

### CODE REVIEW

**Comment by VaclavElias** [comment]
With the latest commit, this reduces the Stride Docs warnings to **79**.

**Comment by VaclavElias** [comment]
Hello, can this be merged?

**Review by Jklawreszuk — APPROVED** [review]
Looks legit to me 👌😃

**Comment by VaclavElias** [comment]
Thanks for checking this for me @Jklawreszuk. Please, can this be merged, so we can improve our docs?

**Comment by Eideren** [comment]
Thanks !

**Pull request merged**
