### PR TITLE
remove stylecop

### PR DESCRIPTION
**Pull request by IXLLEGACYIXL**
# PR Details

Removes  Stylecop from stride completely and the removal of analyzers

## Description

Style Cop gets currently added to the projects, then it gets immediately removed from the analyzers.
if style Cop is enabled again it would generate 22k warnings so it has to stay disabled.

## Related Issue

(https://github.com/stride3d/stride/pull/2104)
Discussion here

## Motivation and Context

Its currently useless as it gets added and then removed.

## Types of changes

- [x] Docs change / refactoring / dependency upgrade
- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist

- [ ] My change requires a change to the documentation.
- [ ] I have added tests to cover my changes.
- [x] All new and existing tests passed.
- [x] **I have built and run the editor to try this change out.**

### CODE REVIEW

**Comment by Eideren** [comment]
Added context for Xen2; removing `DisableAnalyzersForStrideBuild` is done to allow our analyzers and other third party analyzers from nuget to work by default instead of having to whitelist them. No other use or reference of `StrideEnableCodeAnalysis` were found in the code base.

**Comment by IXLLEGACYIXL** [comment]
even though WHEN stylecop should be used then it should be upgraded to the new one https://github.com/DotNetAnalyzers/StyleCopAnalyzers/ as the old one was updated last time 3 years ago https://github.com/StyleCop/StyleCop

**Comment by IXLLEGACYIXL** [comment]
https://gist.github.com/IXLLEGACYIXL/3c08397b2a6a8d25b2d08c8091fa044c
doesnt build anymore after branch update

**Comment by IXLLEGACYIXL** [comment]
works to build with git clean -xfd and dotnet restore

**Comment by Kryptos-FR** [comment]
I would like a confirmation from @xen2 that it's ok to get rid of style cop. Beside that, LGTM.

**Comment by xen2** [comment]
Sorry for not answering earlier.
I started the D3D11 teamcity build a few days ago and it passed, LGTM!

**Review by xen2 — APPROVED** [review]

**Pull request merged**
