### PR TITLE
[Test] Fixed compiler script test failures and oddities (take 2)

### PR DESCRIPTION
**Pull request by Earthmark**
# PR Details
This fixed the script asset tests that were failing on my local machine. This also addresses a side effect of that failure taking out other tests.

## Description

Fixed the console output not getting reset on a test failure, resulting in other tests failing. Now the output is always reset. _Further improvements may be to avoid using console, as it's a singleton and they cause exactly this problem._

Fixed compilation failing in dotnet 6, due to missing a reference to an assembly containing Console or System.Runtime. The following dependencies are now used:
 * `System.Runtime.dll` - Needed for type Object and Decimal, these are specifically not System.Object, it's something else (I'm not sure what).
 * `System.Console.dll` - Needed for System.Console.
 * `System.Private.CoreLib.dll` - Needed for System.Object, System.Void, and other things.

My guess is previously these were all covered by mscorelib or a similar framework-ish assembly.

Testing to ensure these assemblies are available on the target platforms likely needs to happen, I'm curious what the CI system thinks of this.

## Related Issue

None found, this was an issue found while trying to get the tests running locally.

## Motivation and Context

This was found while trying to get the unit tests to run, they did not run successfully on my machine.

## Types of changes

- [ ] Docs change / refactoring / dependency upgrade
- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist

- [ ] My change requires a change to the documentation.
- [x] I have added tests to cover my changes.
- [ ] All new and existing tests passed.
_The tests pass locally where as they failed previously, CI verification is needed as this seems like a platform dependency thing._

### CODE REVIEW

**Comment by Earthmark** [comment]
Seems like most of the builds passed, all's good.

**Comment by Eideren** [comment]
I can't repro on my machine, before I merge this in could you write a small repro of what you did and what the console output was be it error or weirdness for posterity ?

**Comment by Earthmark** [comment]
This comes up based on these steps:
* Compile using compile.bat
* Change directory to `sources\engine\Stride.Assets.Tests`
* run `dotnet test` _or_ `Stride.Assets.Tests` in the visual studio test runner (The errors happen in both)

I get a few of this flavor of error:
```
  Failed Stride.Assets.Tests.TestVisualScriptCompiler.TestVariableGet [747 ms]
  Error Message:
   System.InvalidOperationException : Compilation errors:
(8,9): error CS0234: The type or namespace name 'Console' does not exist in the namespace 'System' (are you missing an assembly reference?)
(11,13): error CS0234: The type or namespace name 'Console' does not exist in the namespace 'System' (are you missing an assembly reference?)

  Stack Trace:
     at Stride.Assets.Tests.TestVisualScriptCompiler.CreateInstance(SyntaxTree[] syntaxTrees) in C:\Users\earth\source\repos\Earthmark\stride\sources\engine\Stride.Assets.Tests\TestVisualScriptCompiler.cs:line 226
   at Stride.Assets.Tests.TestVisualScriptCompiler.TestAndCompareOutput(VisualScriptAsset visualScriptAsset, String expectedOutput, Action`1 testCode) in C:\Users\earth\source\repos\Earthmark\stride\sources\engine\Stride.Assets.Tests\TestVisualScriptCompiler.cs:line 191      
   at Stride.Assets.Tests.TestVisualScriptCompiler.TestVariableGet() in C:\Users\earth\source\repos\Earthmark\stride\sources\engine\Stride.Assets.Tests\TestVisualScriptCompiler.cs:line 114
```

I also get a few of these errors, I believe due to Console getting mangled by the previous failures.
```
  Failed Stride.Assets.Tests.TestMaterialGenerator.TestSimpleNoLayer [< 1 ms]
  Error Message:
   System.ObjectDisposedException : Cannot write to a closed TextWriter.
  Stack Trace:
     at System.IO.StringWriter.Write(String value)
   at System.IO.TextWriter.WriteLine(String value)
   at System.IO.TextWriter.SyncTextWriter.WriteLine(String value)
   at System.Console.WriteLine(String value)
   at Stride.Assets.Tests.TestMaterialGenerator.AssertShaderSourceEqual(String expected, ShaderSource shaderSource) in C:\Users\earth\source\repos\Earthmark\stride\sources\engine\Stride.Assets.Tests\TestMaterialGenerator.cs:line 942
   at Stride.Assets.Tests.TestMaterialGenerator.TestSimpleNoLayer() in C:\Users\earth\source\repos\Earthmark\stride\sources\engine\Stride.Assets.Tests\TestMaterialGenerator.cs:line 91
```

I'm getting some odd build errors with VS now, depending on if I compile the project using compile.bat first or not... looking more into that.

**Comment by Eideren** [comment]
Thanks !

**Pull request merged**
