### PR TITLE
[Build] Restore rules on stride analysers

### LINKED ISSUE #2073: StrideCompilerServices doesnt resolve
**Release Type**: 
Current git state
**Version**: 
4.2

**Platform(s)**: Does the problem occur on Windows, Android...?

**Describe the bug**
No project can resolve the CompilerServices even though every project should
grafik

**To Reproduce**
1. get latest stride
2. check analysetools if stride compilerservices is there
3. its not there

**Expected behavior**
every project should have it as analyse tool and it should show the rolsyn diagnostics

### PR DESCRIPTION
**Pull request by Kryptos-FR**
This was preventing them from being included in all projects.

## Related Issues

Fixes #2073. Partially reverts #2061.

Related to #2045, #2052, and #2055.

## Types of changes

- [ ] Docs change / refactoring / dependency upgrade
- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist

- [ ] My change requires a change to the documentation.
- [ ] I have added tests to cover my changes.
- [ ] All new and existing tests passed.
- [x] **I have built and run the editor to try this change out.**

### CODE REVIEW

**Comment by Kryptos-FR** [comment]
Please run a build on TeamCity before merging.

**Comment by xen2** [comment]
> Please run a build on TeamCity before merging.

Looks like Eideren ran them and everything looks good.
Should I merge?

**Comment by Kryptos-FR** [comment]
> Should I merge?

It's not critical for the 4.2 release. So I guess we can wait a bit.

**Comment by Eideren** [comment]
Sounds like its ready for merge now that 4.2 is out, can I go ahead ?

**Pull request merged**
