### PR TITLE
feat: Update samples/template to top-level statements

### PR DESCRIPTION
**Pull request by Jklawreszuk**
# PR Details

## Description

This PR applies top-level statements to samples and template generator to generate less boilerplate code

## Types of changes

- [ ] Docs change / refactoring / dependency upgrade
- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist

- [ ] My change requires a change to the documentation.
- [ ] I have added tests to cover my changes.
- [ ] All new and existing tests passed.
- [x] **I have built and run the editor to try this change out.**

### CODE REVIEW

**Comment by Kryptos-FR** [comment]
I would keep the namespace though.

It can be a single line as well, for instance:
```csharp
using Stride.Engine;

namespace SimpleAudio;

using var game = new Game();
game.Run();
```

**Comment by VaclavElias** [comment]
I have been removing gradually namespaces from everywhere in my all C# projects **start up files**. I haven't had yet the need to reverse or wonder what namespace should be there.

Empty end line should be consistent across solution, that's right.

**Comment by Jklawreszuk** [comment]
@Kryptos-FR Done and its ready to merged 😊

**Review by Kryptos-FR — APPROVED** [review]

**Comment by Eideren** [comment]
Thanks !

**Pull request merged**
