### PR TITLE
fix: [DirectoryWatcher] - Folders are case sensitive on Linux

### PR DESCRIPTION
**Pull request by Jklawreszuk**
# PR Details

For some reason Path is transformed to lowercase, but on Linux distros it causes a runtime error - "The directory name .... does not exist" during game runtime.

## Types of changes

- [ ] Docs change / refactoring / dependency upgrade
- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist

- [ ] My change requires a change to the documentation.
- [ ] I have added tests to cover my changes.
- [ ] All new and existing tests passed.
- [ ] **I have built and run the editor to try this change out.**

### CODE REVIEW

**Comment by Eideren** [comment]
Wouldn't it make sense to remove the `ToLowerInvariant` call entirely ? If it works on linux it will work on windows since it is the more lenient of the two ? Or do we have some specific handling per os here that breaks this assumption ?

**Comment by IXLLEGACYIXL** [comment]
```
                if (needProjectReload == false
                    && ((e.ChangeType == FileEventChangeType.Deleted || e.ChangeType == FileEventChangeType.Renamed || e.ChangeType == FileEventChangeType.Created)
                    && Path.GetExtension(changedFile)?.ToLowerInvariant() == ".cs"
                    && changedFileDirectoryName.StartsWith(directoryName, StringComparison.OrdinalIgnoreCase)))
                {
                    needProjectReload = true;
                }
```
would break other parts that have path comparisons

**Comment by Eideren** [comment]
That example would not break on windows afaict though, on linux it may if you have two directory whose name differs only in character casing. What would break on windows is string comparison without `IgnoreCase` specified.

**Comment by IXLLEGACYIXL** [comment]
on linux it needs  a ordinal comparison, on windows it doesnt matter

**Comment by Jklawreszuk** [comment]
What, then, do you finally suggest? I would like to avoid regression thus I added a IsLinux condition to not break anything

**Comment by Eideren** [comment]
Okay, probably best to leave this for later, can you add a small comment above those lines mentioning that it might be safe to remove that check but to investigate that further on windows ?

**Comment by Jklawreszuk** [comment]
Yeah, taking small steps 😅 Alright , I've added a TODO comment as you suggested.

**Comment by Eideren** [comment]
Thanks !

**Pull request merged**
