### PR TITLE
created a basic class to test points

### PR DESCRIPTION
**Pull request by soorMSWE**
# PR Details

I was looking through places to add testing in the game engine and found that there were no tests for the Point class in Stride.Mathematics. In order to add completeness and increase code coverage of the system, I figured I would add a couple simple tests _just_ to make sure that the points are working as they are supposed to.

## Description

I added a couple simple tests for the Point class in Stride.Mathematics. They are very basic and can be added to or modified if desired.

## Related Issue

There is no issue related to this pull request.

## Motivation and Context

This change is not required. I simply added a couple tests to increase code coverage of the project.

## Types of changes

- [ ] Docs change / refactoring / dependency upgrade
- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist

- [ ] My change requires a change to the documentation.
- [ ] I have added tests to cover my changes.
- [x ] All new and existing tests passed.
- [x ] **I have built and run the editor to try this change out.**

### CODE REVIEW

**Comment by soorMSWE** [comment]
@dotnet-policy-service agree

**Comment by Eideren** [comment]
Hey, thanks a bunch for contributing ! Just a note, since those tests expect those 3 points to be constant I think it would be more appropriate to mark them as `readonly` or you could instead move them inside the scope of each function, as you want. That way there is no ambiguity as to their usage.

**Comment by soorMSWE** [comment]
Sure, I will do that right now. Thank you for the feedback!

**Comment by Eideren** [comment]
Looks good, thanks !

**Pull request merged**
