### PR TITLE
Updated models to use stride logo

### PR DESCRIPTION
**Pull request by salahchafai**
# PR Details
edited the mannequin model (removed the xenko logo and changed it with stride's) and created the 3 texture maps for the box (mask, occlusion, normal)
ice_screenshot_20200701-200143
ice_screenshot_20200701-200914

### CODE REVIEW

**Comment by xen2** [comment]
Thank you so much!

**Comment by tebjan** [comment]
i am getting this warning now, when building Stride:
`warning 46,035s: [AssetCompiler] 37 node(s) were present in model [C:/Dev/vvvv/stride/sources/data/tests/knight/scenes/mannequinModel.fbx] but not in asset [mannequinModel Skeleton], please reimport: Armature, CATRigAnkleleft_end, left_extra_bone_end, CATRig1Boneside01_end, CATRig1Boneside324_end, CATRig1Bonelowleft_end, backplatelieftdown_end, CATRigLArmDigit13_end, CATRigLArmDigit23_end, CATRigLArmDigit33_end, CATRigLArmDigit43_end, CATRigLArmDigit53_end, wepon_bone_L_end, CATRigHub002Bone001_end, CATRigHub002Bone002_end, CATRigHub002Bone003_end, CATRigRibcage0rtee_end, CATRigHub002Bone004_end, CATRigRArmDigit13_end, CATRigRArmDigit23_end, CATRigRArmDigit33_end, CATRigRArmDigit43_end, CATRigRArmDigit53_end, wepon_bone_R_end, gun_barrel_end, gun_bone_magazine_end, CATRigHub001Bone002_end, back platerightdown_end, CATRigAnkleright_end, right_extra_bone_end, CATRig1Boeer643_end, CATRig1Bone43840_end, CATRig1Bonerightlow_end, CATRigLLegPlatform_end, CATRigRLegPlatform_end, CATRigRArmIKTarget_end, CATRigLArmIKTarget_end`

@salahchafai did you check whether all animations and skeletons still work after the model was updated?

**Comment by salahchafai** [comment]
> i am getting this warning now, when building Stride:
> `warning 46,035s: [AssetCompiler] 37 node(s) were present in model [C:/Dev/vvvv/stride/sources/data/tests/knight/scenes/mannequinModel.fbx] but not in asset [mannequinModel Skeleton], please reimport: Armature, CATRigAnkleleft_end, left_extra_bone_end, CATRig1Boneside01_end, CATRig1Boneside324_end, CATRig1Bonelowleft_end, backplatelieftdown_end, CATRigLArmDigit13_end, CATRigLArmDigit23_end, CATRigLArmDigit33_end, CATRigLArmDigit43_end, CATRigLArmDigit53_end, wepon_bone_L_end, CATRigHub002Bone001_end, CATRigHub002Bone002_end, CATRigHub002Bone003_end, CATRigRibcage0rtee_end, CATRigHub002Bone004_end, CATRigRArmDigit13_end, CATRigRArmDigit23_end, CATRigRArmDigit33_end, CATRigRArmDigit43_end, CATRigRArmDigit53_end, wepon_bone_R_end, gun_barrel_end, gun_bone_magazine_end, CATRigHub001Bone002_end, back platerightdown_end, CATRigAnkleright_end, right_extra_bone_end, CATRig1Boeer643_end, CATRig1Bone43840_end, CATRig1Bonerightlow_end, CATRigLLegPlatform_end, CATRigRLegPlatform_end, CATRigRArmIKTarget_end, CATRigLArmIKTarget_end`
> 
> @salahchafai did you check whether all animations and skeletons still work after the model was updated?
> @xen2 or do all places that use the model need re-building now?

before sumitting the pr i tried building the engine and it worked just fine, all i changed is the models so there shouldn't be any error, tho i'll try rebuilding now to see what's the issue

**Comment by tebjan** [comment]
yes, this warning is from the asset compiler, it is not a code compilation error. so did you test (build and run) the games/templates that use that model?

**Comment by salahchafai** [comment]
@tebjan you mean when creating a project from a template then starting it ? i only tested that with the fps template, for the rest i only created a project to see whether the models are showing properly or not but didn't build the game, i'll rebuild stride and try that, tho it shouldn't be hard to fix anyway, just reimporting the animated models

**Comment by tebjan** [comment]
Ok, if you checked a game that uses that asset and the animations all work, then it's fine, I guess.

**Comment by xen2** [comment]
I checked: it's working (with the aforementioned warning).
However, if I reimport a material is not set. Also probably animation match because node order is the same, but it's not great that nodes name are different.
For now I will revert the mannequin model so that we can take another closer look at it later.

**Comment by salahchafai** [comment]
i think i understand the issue, in the first pr i edited all the mannequin models i found to have the stride logo, in the second pr i found another mannequin model still with the xenko logo so i just overidden it with another one that has the stride logo, however i think the model that i changed last time doesn't have the same node names as the other ones which is what caused the issue, i'll fix it

**Comment by tebjan** [comment]
@salahchafai that's a good idea, maybe the models where different. Now the question is do we unify both and reimport, or just update the second one add well?

**Comment by salahchafai** [comment]
@tebjan i'm not sure tbh but i think unifying both models would be better, there's no reason for having 2 different models for the mannequin (there are 5 different fbx files but only one of them has the nodes' names different that's why changing it to be like the others would be better)

**Comment by salahchafai** [comment]
@xen2 which material isn't assigned when reimporting the asset ? (i'm replying late cuz i had some issues building stride), i reimported the mannequin and all materials are working fine for me

**Pull request merged**
