### PR TITLE
feat: New areas added

### PR DESCRIPTION
**Pull request by VaclavElias**
# PR Details

Areas added based on the new GitHub labels and some emojis changed.

- Added: area-Core, area-Math, area-Serialization
- Emojis changed: area-Graphics, area-UI, area-Rendering

## Related Issue

N/a

## Types of changes

- [x] Docs change / refactoring / dependency upgrade
- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist

- [x] My change requires a change to the documentation.
- [ ] I have added tests to cover my changes.
- [ ] All new and existing tests passed.
- [ ] **I have built and run the editor to try this change out.**

### CODE REVIEW

**Comment by Eideren** [comment]
Thanks a bunch for looking into this, forgot to mention that rendering has been removed since it overlaps with graphics ...

**Comment by VaclavElias** [comment]
You are welcome. No problem, let me update it :)

**Comment by VaclavElias** [comment]
Done. You can merge it whenever 🥳.

**Comment by Eideren** [comment]
Thanks !

**Pull request merged**
