### PR TITLE
[Font] Update SharpFont library for additional fixes

### PR DESCRIPTION
**Pull request by Basewq**
# PR Details

Successor to #2281 
Must wait until pull at https://github.com/stride3d/SharpFont/pull/1 is merged and its nuget package has been updated to 1.0.1.

My understanding of Stride's build of SharpFont:
* vonderborch's repo, aka [SharpFont.NetStandard](https://github.com/vonderborch/SharpFont) did not contain any major changes compared to Robmaister's repo- it mainly moved files around (no code changes) and the single code change involved loading/switching 32bit/64bit dll, which Stride already does (I think). So the above pull only merged and modified from the latest of Robmaister's repo.
* Stride does not use `freetype6` as provided in Robmaister's branch which is only on v2.6 - Stride uses v2.6.3 https://github.com/stride3d/freetype/tree/2.6.3 (and is named `freetype`), as per this https://github.com/stride3d/stride/blob/master/deps/freetype/checkout.bat

## Types of changes

- [ ] Docs change / refactoring / dependency upgrade
- [X] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist

- [ ] My change requires a change to the documentation.
- [ ] I have added tests to cover my changes.
- [ ] All new and existing tests passed.
- [X] **I have built and run the editor to try this change out.**

### CODE REVIEW

**Comment by Eideren** [comment]
You're a god send, thanks a ton for taking over this one @Basewq and for looking into this further than I had :)

**Comment by Eideren** [comment]
I'll look into publishing the package once teamcity is up

**Comment by Basewq** [comment]
Ready to merge. While there are some fixes within SharpFont, none appears to have impacted Stride at this time, so consider this more of a future proofing update.

Realistically, if there are font bugs that need fixing, consider updating the stride version of freetype repo: https://github.com/stride3d/freetype

**Comment by Eideren** [comment]
Thanks !

**Pull request merged**
