### PR TITLE
Update README badges

### PR DESCRIPTION
**Pull request by Jklawreszuk**
# PR Details

As the title suggests.

### CODE REVIEW

**Comment by VaclavElias** [comment]
And this is how it looks like

[Join the chat at https://discord.gg/f6aerfE](https://discord.gg/f6aerfE)
[All Contributors](#contributors)
[Financial sponsors](https://opencollective.com/stride3d)
[License](https://github.com/stride3d/stride/blob/master/LICENSE.md)

**Comment by Jklawreszuk** [comment]
*except it's inline. I also changed discord logo color for better contrast 👍

**Comment by VaclavElias** [comment]
It is definitely better

**Comment by VaclavElias** [comment]
Can we merge this?

**Pull request merged**
