### PR TITLE
Added Clone method to ViewportState and copy parameter to ViewportRestore constructor

### PR DESCRIPTION
**Pull request by Artromskiy**
# PR Details

Added Clone method to ViewportState and copy parameter to ViewportRestore constructor

## Description

Done to fix issue of not correctly working render texture

## Related Issue

https://github.com/stride3d/stride/issues/1069

## Motivation and Context

https://github.com/stride3d/stride/issues/1069

## Types of changes

- [ ] Docs change / refactoring / dependency upgrade
- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist

- [ ] My change requires a change to the documentation.
- [ ] I have added tests to cover my changes.
- [ ] All new and existing tests passed.

### CODE REVIEW

**Comment by Eideren** [comment]
Maybe you could make ``ViewportState`` into a struct ? I haven't looked thoroughly at the source but it sounds like that would be preferable given that it is cloned fairly often and so generates a bit of unnecessary garbage for the GC to churn through ? Pinging @vdvman1 in case he has more insight into this.

**Comment by Artromskiy** [comment]
Changing ViewportState to struct also works

**Comment by Eideren** [comment]
Great, thanks ! It seems safe so I'll just merge this in, we'll revert and come back to this if it ever becomes an issue

**Comment by tebjan** [comment]
Very good one, we had a few bugs because of this... Thanks!

**Pull request merged**
