### PR TITLE
Make editing projects easier.

### PR DESCRIPTION
**Pull request by ericwj**
Make editing projects easier.

Guess what Visual Studio does to the poor people whose indentation is set to Tabs by default...

### CODE REVIEW

**Comment by NicusorN5** [comment]
Tabs > Spaces

**Comment by tebjan** [comment]
do they all use only two spaces?

**Comment by ericwj** [comment]
The one `.pbxproj` uses tabs.

**Comment by tebjan** [comment]
Great, thanks a lot!

**Pull request merged**
