### PR TITLE
Update : geometric primitive.cylinder to avoid GC

### PR DESCRIPTION
**Pull request by Arc-huangjingtong**
# PR Details

## Types of changes

- [x] Docs change / refactoring / dependency upgrade
- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist

- [ ] My change requires a change to the documentation.
- [ ] I have added tests to cover my changes.
- [ ] All new and existing tests passed.
- [x] **I have built and run the editor to try this change out.**

### CODE REVIEW

**Comment by Arc-huangjingtong** [comment]
image
Test Success

**Comment by Eideren** [comment]
Thanks !

**Comment by Arc-huangjingtong** [comment]
You're welcome. I'm happy to help

**Comment by Kryptos-FR** [comment]
Note for later: I see a lot of code-style change that don't conform to the rest of the code base and will likely be changed again the next time the file is touched. Please refrain form using your "preferred code style" and stick to what is currently present.

For instance, we never align statements by adding additional spaces before the `=` sign.

**Comment by Arc-huangjingtong** [comment]
> Note for later: I see a lot of code-style change that don't conform to the rest of the code base and will likely be changed again the next time the file is touched. Please refrain form using your "preferred code style" and stick to what is currently present.
> 
> For instance, we never align statements by adding additional spaces before the `=` sign.

Yes， I remember

**Pull request merged**
