### PR TITLE
Update launcher brand icons

### PR DESCRIPTION
**Pull request by minktusk**
# PR Details

Replace old brand icons for new brand icons

## Related Issue

Any, just some icons change

## Types of changes

- [x] Docs change / refactoring / dependency upgrade
- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist

- [ ] My change requires a change to the documentation.
- [ ] I have added tests to cover my changes.
- [ ] All new and existing tests passed.
- [ ] **I have built and run the editor to try this change out.**

### CODE REVIEW

**Comment by Jklawreszuk** [comment]
Thanks, It looks like this is your first PR. I have a question, where did you get the social icons from? Unfortunately, some look to be of lesser quality than the old ones

**Comment by minktusk** [comment]
I get them from the official brand pages, then a resize it

**Comment by VaclavElias** [comment]
Could we use SVG, if XAML supports that?

**Comment by Doprez** [comment]
https://uxwing.com/x-social-media-round-icon/
Im not sure if these are better for quality @Jklawreszuk but it seems like the licenses should be good.

They also provide SVG if you want to try that route and see how they are.

**Comment by Jklawreszuk** [comment]
@minktusk Oh, I see. Like @Doprez suggested, try to find SVG images and try to export them into png files (i.e using Inkscape) - this way you can be sure that the images will be rendered correctly :)
Don't forget to add the license to these logos in the https://github.com/stride3d/stride/blob/master/LICENSE.md file 😊

**Comment by Jklawreszuk** [comment]
If WPF supports SVG file format then you can also replace pngs directly if you wish so. It shouldn't cause much lag

**Comment by minktusk** [comment]
Thanks, I will try change the icons for SVG and see if it works properly!

**Comment by minktusk** [comment]
Sorry for taking so long to update this pull request. I wasn't able to make it run SVG files. Honestly, I don't know if it's because XAML doesn't have support for it, or because I just don't know how to use XAML with SVG. So instead of using SVG, I just export them all to PNG using Inkscape ( Recommended by @Jklawreszuk ).

PS: I also changed all mentions in the code from Twitter to XTwitter!

**Comment by VaclavElias** [comment]
I found this (also as NuGet) but have no experience with it, also not sure if there are other alternatives. Probably, we should keep whatever has less gears and is easier to maintain?

https://elinamllc.github.io/SharpVectors/

**Comment by Eideren** [comment]
Not sure about svg but xaml supports embedded vectors, see https://github.com/stride3d/stride/blob/master/sources/editor/Stride.Assets.Presentation/View/ImageDictionary.xaml
There's a couple of tools built to make the conversion, lookup `svg to xaml`
In any case, having them as bitmaps is fine too, I'll merge this one with the rest this week end

**Comment by Eideren** [comment]
Thanks !

**Pull request merged**
