### PR TITLE
[Build] Add .vsconfig to check missing requirements in VS

### PR DESCRIPTION
**Pull request by Eideren**
# PR Details
See #1312 , didn't/can't test but should be working

## Types of changes
- [ ] Docs change / refactoring / dependency upgrade
- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist
- [ ] My change requires a change to the documentation.
- [ ] I have added tests to cover my changes.
- [x] All new and existing tests passed.

### CODE REVIEW

**Comment by tebjan** [comment]
The list of workloads looks a bit long to me... are you sure that we need all of these?

**Comment by Eideren** [comment]
The engine might only need a subset of these but this list is what VS installer generates for the workloads listed in our readme, better safe than sorry so I kept it as is.
Just as a note, each requirement listed in the readme generates multiple workloads, `Desktop development with C++` alone for example takes around 1/3 of that list.

**Comment by tebjan** [comment]
Ah I see, didn't know how that works in detail. maybe @xen2 would be better to review this.

**Comment by Eideren** [comment]
I initially created it with VS tools but tools and studio configurations aren't shared, this version should work for Studio.

**Comment by jrinker03** [comment]
I've tested this change with a fresh installation of VS with few of the prereqs installed and it works as expected:
image

Clicking on 'Install' opens the VS Installer with the workloads and components selected as expected:

image

After VS reopens, the solution builds completely.

**Comment by Eideren** [comment]
Thanks a bunch for testing this out @jrinker03 ! I'll merge this in then since it's quite safe. If Xen ever has time to take a look later we'll update accordingly.

**Pull request merged**
