### PR TITLE
Replace NativeStream with BinaryWriter

### PR DESCRIPTION
**Pull request by IXLLEGACYIXL**
# PR Details

Removing NativeStream.
Replacing it with Binarywriter and BinaryReader

## Description

As the IO is just a self implemented Version of what allready exist it can be replaced.

## Motivation and Context

Removes the unnecessary implementation of IO operations when .NET anyway provides a fast alternative
Second attempt as the first one resulted in having the implementation of Binarywriter copy pasted.

## Types of changes

- [ ] Docs change / refactoring / dependency upgrade
- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist

- [ ] My change requires a change to the documentation.
- [ ] I have added tests to cover my changes.
- [x] All new and existing tests passed. ( couldnt test the Windows image comparison tests but i didnt change there something .. fail also before my commits )

### CODE REVIEW

**Comment by IXLLEGACYIXL** [comment]
all tests have passed for now and i was able to launch my game without problems

all i did for now was replacing the reads and writes with the binary writer

**Comment by Eideren** [comment]
Nice, if you're done with this PR I'll merge it in ?

**Comment by IXLLEGACYIXL** [comment]
im currently unsure how it will go further.

It can be merged and replacing all the wrappers can be done in a separate PR 
I think it would be a good idea to merge it as removing all the wrappers will be "big" 

As always i would be happy if someone tries it :D

**Comment by IXLLEGACYIXL** [comment]
allright now it would be ready to get tested and if that is successful it can be merged

**Comment by Eideren** [comment]
Yep, tried it out and it works fine, thanks :)

**Pull request merged**
